### ISSUE TITLE
Docker remote API: support older versions

### ISSUE THREAD

**Issue by gdevillele** [docker/dockercraft#21]
Dockercraft currently talks only the latest version of the Docker remote API (docker 1.9), so it doesn't work when using a docker daemon older than 1.9.

from discussion in PR #14

**Comment by mheiniger** [comment]
Please note in the Readme, that its currently for 1.9 only. I was on an older version and had no idea why my interactions with the containers in minecraft did not reach docker.

**Comment by aduermael** [comment]
Yes, we will add a note in the Readme, but a clear error in the logs would be a good thing as well.
