### ISSUE TITLE
Running Docker commands from "T"

### ISSUE THREAD

**Issue by vosmith** [docker/dockercraft#22]
Pressing "T" currently opens the messaging window where you can run Docker commands.  However it was not specified that your commands must be prepended with a `/` (ie `/docker run ...`).  This should either be documented, or the messaging window should support plain old `docker run ...`.

Thoughts?

**Comment by aduermael** [comment]
We should add it in the Readme. 
Prepending with `/` is the official way to run commands in Minecraft, I would prefer to keep supporting that. Especially to be able to show docker commands to friends using the chat, without actually running them.

**Comment by aduermael** [comment]
@vosmith Would adding a mention about this in the Readme solve the issue for you?

**Comment by vosmith** [comment]
Yes sir I that would be perfect👍
