### ISSUE TITLE
Proposal: Destroying containers should make them explode

### ISSUE THREAD

**Issue by dave-tucker** [docker/dockercraft#31]
Because explosions are way cooler than the container disappearing!

**Comment by aduermael** [comment]
If we can contain the explosion I agree. It should not destroy neighbor containers... :) 
And it should not kill the player also! :D

**Comment by dave-tucker** [comment]
:boom: ... I think I'll start working on a prototype :)
If the implementation of #32, moves controls outside of the container this might be a lot safer for the player :)

**Comment by dreddpenguin** [comment]
Put the player in creative mode, and make the floor out of obsidian
Not sure about protecting the other containers
