### ISSUE TITLE
Disable weather simulation

### ISSUE THREAD

**Issue by gdevillele** [docker/dockercraft#43]
maybe we should disable weather simulation so there is no random rain...

![srikrishnaholla_2015-nov-27](https://cloud.githubusercontent.com/assets/939999/11453711/3db76586-95ca-11e5-9d62-90de3ebd2d4e.png)

**Comment by aduermael** [comment]
Or we should localize your host, and apply real weather... :p

**Comment by thaJeztah** [comment]
(packs bags and moves to a sunnier place)
