### ISSUE TITLE
Change Worldseed?

### ISSUE THREAD

**Issue by kleinerpogo** [docker/dockercraft#54]
Hey there,

I would like to change the World-Seed of my Dockercraft-World, would this be possible? Im thinking about just creating a normal Minecraft World, with my Dockercraft Containers isolated in some kind of selfmade Bedrock Formation or something. Would this be possible, would it be possible to generate a new ("normal") world with the Docker Containers in a spot? Cleaning up by hand wouldnt be a problem, though. Im not that into cuberite servers, so I thought, I just ask for some support here :)
Thanks in advance.

~Jan

**Comment by gdevillele** [comment]
Hello, 
sorry for the delay.
It is technically possible.

It is possible to have a world seed with an area which have been manually cleaned and modify dockercraft so the containers in minecraft are generated at the coordinates of this area.

We disabled the map generation in Cuberite, but it is possible to bring it back...
I don't remember if it is possible to customize the map generation, but if it is, it could be fully automatic: bedrock would be generated on the path of the containers ... or we could override existing world with bedrock when we need to add a new container.

Is there an option you would prefer? Then I could assist you if you want.

hardly related, but in case you have not seen this : https://github.com/docker/dockercraft/issues/2

-- Gaetan

**Comment by kleinerpogo** [comment]
Hey there, 
thanks for your fast reply :)

Nah, wouldnt be a problem, if there would be anything around the containers (except lava, i guess.. :D) . Just a random generated world, and the place the containers are in could be modified ingame by hand. I guess, this would be the first step here, anything else after that, maybe :)

Regards
~Pogo

**Comment by nixpulvis** [comment]
I was wondering about this myself. I'm pretty new to minecraft and docker, but I assume the only real hard part is getting the containers to "spawn" correctly.

**Comment by dave-tucker** [comment]
Fixed in #74
