### ISSUE TITLE
Proposol: Creeper Chaos Testing

### ISSUE THREAD

**Issue by yenda** [docker/dockercraft#56]
Docker has made deployment too easy, could you add a mode with creepers destroying dockers to make it a bit more fun ?

**Comment by ginogabriel** [comment]
[Fabric.pdf](https://github.com/docker/dockercraft/files/237280/Fabric.pdf)

**Comment by mercuriete** [comment]
Could be related to: https://github.com/docker/dockercraft/issues/17 ?

**Comment by gdevillele** [comment]
I think it is.

@yenda if you are describing the same feature as the on in #17 , could you close this issue please? 

Thanks.

**Comment by aduermael** [comment]
Closing this one, in favor of  #17. 
But I agree it's a pretty cool idea!

**Comment by mirth** [comment]
Are you kidding? We have kubernetes. Are you not entertained?

**Comment by aduermael** [comment]
😂
