### ISSUE TITLE
Enhancement - Consider supporting other game clients

### ISSUE THREAD

**Issue by ryanmcnz** [docker/dockercraft#7]
Perhaps also have a go at visualizing Docker in games such as mari0 or Garrysmod.
I feel like this would be highly beneficial to the project, and would increase my productivity 500% (especially when I'm visualizing docker with portals).

**Comment by malyavkin** [comment]
Would be nice if you need to migrate container from one server to another. Use that portal gun, poof, never been so easy.

**Comment by grahamc** [comment]
Wouldn't the portal gun be more of an network connection? Either way sounds good.

**Comment by aduermael** [comment]
We can implement portals in Dockercraft... Some servers are implementing this already, convenient for very big maps.

**Comment by victort** [comment]
Minecraft has portals, but they go to the PCI zone.

**Comment by aduermael** [comment]
@victort what's the PCI zone?

**Comment by aduermael** [comment]
Closing as it would be a new project by itself to support another game client.
But it's definitely something to explore someday!
