### ISSUE TITLE
How to craft herokuish? 

### ISSUE THREAD

**Issue by nemanjan00** [docker/dockercraft#72]
What should I put in crafting table to craft herokuish conainer?

**Comment by alibonbon** [comment]
[see example](https://fagken.com)

**Comment by dave-tucker** [comment]
@alibonbon your comment has been removed as it's off-topic and quite frankly inappropriate.
Please see [the community guidelines](https://github.com/docker/docker/blob/master/CONTRIBUTING.md#docker-community-guidelines)
