### ISSUE TITLE
unsupported protocol version

### ISSUE THREAD

**Issue by lholmquist** [docker/dockercraft#80]
I've just built the docker image using the [master branch](8d1259f68a04f1b1d9b439d97d10f45bd74e3c93),  

running minecraft version 1.11.2
docker for mac version 1.13.1
OS X Sierra(10.12.3)

The docker image builds and runs with no errors.

After i do the "add server", which i point to "localhost", then i click on my new server to launch and get the error "Unsupported protocol version 316, please use one of these versions: 1.8.x, 1.9.x, 1.10.x"

**Comment by Seadragon91** [comment]
The newest version of [cuberite](https://github.com/cuberite/cuberite) has support for protocol 1.11, but it's not stable. Please use one of this versions: 1.8.x, 1.9.x, 1.10.

**Comment by lholmquist** [comment]
yea, i figured that was the case,  i'm just going to use the latest build on cuberite's jenkins and see how that goes, https://builds.cuberite.org/job/Cuberite%20Linux%20x64%20Master/697/

**Comment by lholmquist** [comment]
@Seadragon91 where do i find the older client versions?

**Comment by Seadragon91** [comment]
In the minecraft client you should be able to select the version you want to play.

**Comment by lholmquist** [comment]
Ok, got it to work with changing the version inside the minecraft client.  I'll close this for now

**Comment by dave-tucker** [comment]
@lholmquist FYI, I tried with the latest cuberite version this morning and the container wouldn't run.
Looks like there are some missing dependencies ( something to do with `libstdc++`) so the dockerfile will probably need some tweaking

**Comment by RAOdotSH** [comment]
I'm facing the same issue when tho I changed the versions from 1.19.2 to 1.18.2 and 1.19.1.
Help please :pray:
