### ISSUE TITLE
docker minecraft launcher

### ISSUE THREAD

**Issue by weironz** [docker/dockercraft#88]
i'm finding a minecraft launcher for docker, anyone have idea? i just want Hang up all the time , i just run a docker container for ubuntu, and then instlal Minecraft.deb, is there any other way？

**Comment by JBYoshi** [comment]
If you want a Minecraft server, there are a bunch of options on https://hub.docker.com. If you want a client, you’ll probably have to write it yourself - most people only use Docker for server applications.

**Comment by weironz** [comment]
i use this way 
```
docker run -d --restart always --name mclaunch -p 6080:80 -p 5900:5900 dorowu/ubuntu-desktop-lxde-vnc
```
then install minecraft launcher in container
```
官方下载地址
https://www.minecraft.net/zh-hans/download/alternative
ubuntu直接下载
安装参考
https://linuxconfig.org/how-to-install-minecraft-on-ubuntu-18-04-bionic-beaver-linux
curl -O https://launcher.mojang.com/download/Minecraft.deb
apt-get update && apt-get -f -y install
apt install gdebi-core && gdebi Minecraft.deb
或dpkg -i Minecraft.deb

```

**Comment by guillaume130679** [comment]
Current version of JAVA Edition is 1.16 ... the versions supported by dockercraft are quite old.... Any chance that v 1.16.x is getting supported soon? Thanks!

**Comment by lukeawyatt** [comment]
I know this is old, but I have a working client-on-docker utilizing TLauncher - [docker-tlauncher](https://github.com/lukeawyatt/docker-tlauncher)
